version: '3'
services:
  fiber-boilerplate:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
